### PR TITLE
Make explosions:tnt detonate when dispensed

### PR DESCRIPTION
**Pull request by KarlHegbloom**
My son wants tnt cannons. :-)

### CODE REVIEW

**Comment by mdoege** [comment]
Thanks, Karl! Merged. :-)

**Comment by KarlHegbloom** [comment]
You're welcome.  Tnt cannons still don't work. I think tnt had to be an
entity Hebert a placed block so it doesn't displace the water and water
must prevent damage but must provide impetus to throw dropped objects and
players. When I have some time to I want to fix it.

**Comment by mdoege** [comment]
TNT already becomes an entity in my game when it is lit. So if in water it should call a function that only does player knockback (relative to its position) and does not cause damage to blocks/players.

Arrows (in the throwing mod) could also use a knockback effect, so maybe they could call the same function.

By the way, the real Stampy just observed a few weeks ago that TNT cannons no longer work in MC after the last update. I don't know if that is a bug or intentional. So I guess MT is on par with MC on the Xbox 360 at least. :-)

**Comment by HybridDog** [comment]
You could add a shield to the tnt (via crafting). If an explosion happens the shield gets destroyed. If a tnt next to it explodes, its shield gets destroyed and it flies and explodes after a bit time (tnt cannon). The disadvantage of the shielded tnt is when one gets lit and explodes, it disappears and doesn't cause destruction.

**Comment by mdoege** [comment]
Oh, I thought you meant TNT cannons that launch players up in the air (which turn out to be impossible in MT because there are no setacceleration() and setvelocity() methods for players).

As for launching TNT blocks themselves, you can already do that if you light several TNT blocks close by in quick succession. The first block explodes and sends the second block (which is an entity when lit) flying away.

I've pushed a fix for TNT in water causing player damage though. That was a bug.

**Comment by mdoege** [comment]
P.S. Maybe one could crudely simulate player knockback with setpos() instead. It would look more like an instantaneous transport away from the TNT though.

**Comment by HybridDog** [comment]
>P.S. Maybe one could crudely simulate player knockback with setpos() instead. It would look more like an instantaneous transport away from the TNT though.

You could attach the player to an invisible object.

**Comment by KarlHegbloom** [comment]
Martin, I think that there needs to be setacceleration() and setvelocity()
methods for players then. How does it make the player fall due to gravity
when you use fly mode, hold down space to fly up high, and then press k to
turn fly mode off? It seems like that must need to use g, and thus there's
an acceleration and velocity change.

Also, in free fall, why can I push w a s d and move? If I can do that, then
in player view mode, I should see him in sky-diving control position,
right? The parachute mod is cool. It's easy enough to understand... but it
has to keep track of the velocities etc. for some reason... But it can
retrieve them; So why not set them also, for knock-back?

On Mon, Jan 11, 2016 at 9:59 AM, HybridDog <notifications@github.com> wrote:

> P.S. Maybe one could crudely simulate player knockback with setpos()
> instead. It would look more like an instantaneous transport away from the
> TNT though.
>
> You could attach the player to an invisible object.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdoege/stampy_game/pull/2#issuecomment-170617907>.
>



-- 
Karl.Hegbloom@gmail.com
http://karlhegbloom.blogspot.com

**Comment by mdoege** [comment]
Yes, the player object is a bit special and lacks some methods. Maybe they will get added later, ask the MT devs.

But attaching the player to an object works; I can launch myself in the air now! Great idea. Still needs a bit more work, but so far so good. Git push is coming soon.

**Comment by KarlHegbloom** [comment]
Nice. Like "capes" and "parachute" mod do, to attach an object to a player?

On Mon, Jan 11, 2016 at 11:40 AM, Martin C. Doege <notifications@github.com>
wrote:

> Yes, the player object is a bit special and lacks some methods. Maybe they
> will get added later, ask the MT devs.
>
> But attaching the player to an object works; I can launch myself in the
> air now! Great idea. Still needs a bit more work, but so far so good. Git
> push is coming soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdoege/stampy_game/pull/2#issuecomment-170647930>.
>



-- 
Karl.Hegbloom@gmail.com
http://karlhegbloom.blogspot.com

**Comment by mdoege** [comment]
I've looked at the boat mod as you suggested. I'll have to look for the capes and parachutes mods, sounds interesting.

**Comment by KarlHegbloom** [comment]
https://github.com/webdesigner97/parachute
https://github.com/4aiman/capes.git

On Mon, Jan 11, 2016 at 12:08 PM, Martin C. Doege <notifications@github.com>
wrote:

> I've looked at the boat mod as you suggested. I'll have to look for the
> capes and parachutes mods, sounds interesting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdoege/stampy_game/pull/2#issuecomment-170655332>.
>



-- 
Karl.Hegbloom@gmail.com
http://karlhegbloom.blogspot.com

**Comment by mdoege** [comment]
Thanks! Doesn't work too well in stampy_game; the cape has no texture and the parachute is not in creative inventory. Probably only works with minetest_game?

**Comment by KarlHegbloom** [comment]
Wool wool wool
Cotton        cotton
           Stick

**Comment by mdoege** [comment]
No description text was defined for parachute items, therefore my search did not work…

**Pull request merged**
